<?php

return [
    'modules' => [
        ['prefix' => 'admin/dashboard', 'view' => 'view_dashboard'],
        ['prefix' => 'admin/companies', 'view' => 'view_companies', 'create' => 'create_companies', 'edit' => 'edit_companies', 'delete' => 'delete_companies', 'approve' => 'approve_companies'],
        ['prefix' => 'admin/users', 'view' => 'view_users', 'create' => 'create_users', 'edit' => 'edit_users', 'delete' => 'delete_users'],
        ['prefix' => 'admin/bookings', 'view' => 'view_bookings', 'create' => 'create_bookings', 'edit' => 'edit_bookings', 'approve' => 'approve_bookings', 'delete' => 'cancel_bookings'],
        ['prefix' => 'admin/shipments', 'view' => 'view_shipments', 'create' => 'create_shipments', 'edit' => 'edit_shipments'],
        ['prefix' => 'admin/invoices', 'view' => 'view_invoices', 'create' => 'create_invoices', 'edit' => 'edit_invoices', 'approve' => 'approve_invoices', 'delete' => 'void_invoices'],
        ['prefix' => 'admin/payments', 'view' => 'view_payments', 'create' => 'manage_payments', 'edit' => 'manage_payments'],
        ['prefix' => 'admin/vendors', 'view' => 'view_vendors', 'create' => 'manage_vendors', 'edit' => 'manage_vendors'],
        ['prefix' => 'admin/pricing', 'view' => 'view_pricing', 'create' => 'edit_pricing', 'edit' => 'edit_pricing'],
        ['prefix' => 'admin/vendor-job-orders', 'view' => 'view_vendor_job_orders_admin', 'create' => 'manage_vendor_job_orders_admin', 'edit' => 'manage_vendor_job_orders_admin'],
        ['prefix' => 'admin/vendor-invoices', 'view' => 'view_vendor_invoices_admin', 'create' => 'manage_vendor_invoices_admin', 'edit' => 'manage_vendor_invoices_admin'],
        ['prefix' => 'admin/vendor-payments', 'view' => 'view_vendor_payments_admin', 'create' => 'manage_vendor_payments_admin', 'edit' => 'manage_vendor_payments_admin'],
        ['prefix' => 'admin/containers', 'view' => 'view_containers', 'create' => 'manage_containers', 'edit' => 'edit_containers'],
        ['prefix' => 'admin/container-movements', 'view' => 'view_containers'],
        ['prefix' => 'admin/operation-tasks', 'view' => 'view_operations', 'create' => 'manage_operations', 'edit' => 'manage_operations'],
        ['prefix' => 'admin/proof-of-deliveries', 'view' => 'view_operations', 'create' => 'manage_operations', 'edit' => 'manage_operations'],
        ['prefix' => 'admin/routes', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/stations', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/yards', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/train-schedules', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/customer-pricings', 'view' => 'manage_pricing', 'create' => 'manage_pricing', 'edit' => 'manage_pricing'],
        ['prefix' => 'admin/additional-charges', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/transport-modes', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/service-types', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/container-types', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/additional-services', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/trains', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/train-cars', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/cargo-categories', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/dg-classes', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/locations', 'view' => 'manage_master_data', 'create' => 'manage_master_data', 'edit' => 'manage_master_data'],
        ['prefix' => 'admin/reports', 'view' => 'view_reports', 'export' => 'export_reports'],
        ['prefix' => 'admin/roles', 'view' => 'manage_roles', 'create' => 'manage_roles', 'edit' => 'manage_roles'],
        ['prefix' => 'admin/permissions', 'view' => 'manage_roles'],
        ['prefix' => 'admin/settings', 'view' => 'view_settings', 'edit' => 'manage_settings'],
        ['prefix' => 'admin/numbering-formats', 'view' => 'manage_numbering', 'edit' => 'manage_numbering'],
    ],
];
